Repository aeternity/aepp-playground, pull requests merged in 2019-05, with the labels that each got.

#112 upgrade packages and fix lints
  package-lock.json
  package.json
  src/components/aepp-iframe.vue
  src/plugins/editor.js
Labels: review

#113 Merge devеlop into master
  .env
  .env.production
  package-lock.json
  package.json
  src/aepp.vue
  src/components/aepp-editor.vue
  src/components/aepp-iframe.vue
  src/main.js
  src/plugins/editor.js
  src/plugins/wallet.js
  src/sections/aepp-terminal.vue
  src/store/actions/index.js
  src/store/modules/contracts/mutations.js
  src/store/modules/contracts/state.js
  src/store/modules/index.js
  src/store/modules/terminal/actions.js
  src/store/modules/terminal/getters.js
  src/store/modules/terminal/index.js
  src/store/modules/terminal/mutations.js
  src/store/modules/terminal/state.js
  src/store/mutations/index.js
  src/store/state/index.js
  src/views/editor/index.vue
  src/views/routes.js
Labels: review

#115 Hotfix/fix aepp components package and vulnerability
  package-lock.json
  package.json
  src/aepp.vue
  src/components/aepp-collapse.vue
  src/components/aepp-input.vue
  src/components/aepp-textarea.vue
  src/main.js
  src/views/browser/index.vue
  src/views/configs/index.vue
  src/views/editor/index.vue
  src/views/executor/index.vue
  src/views/explorer/index.vue
  src/views/identity/index.vue
  src/views/inspector/index.vue
  vue.config.js
Labels: review

#116 Add license and author
  LICENSE.md
  package.json
Labels: enhancement, review

#117 Add messages on compile and call functions to the console
  package-lock.json
  src/views/editor/index.vue
Labels: review

#123 Define Sophia language syntax highlighting and register it
  .gitignore
  package-lock.json
  src/components/aepp-editor.vue
  src/plugins/editor.js
  yarn.lock
Labels: review

#125 Playground New Release
  .gitignore
  LICENSE.md
  README.md
  package-lock.json
  package.json
  src/aepp.vue
  src/components/aepp-collapse.vue
  src/components/aepp-editor.vue
  src/components/aepp-input.vue
  src/components/aepp-textarea.vue
  src/main.js
  src/plugins/editor.js
  src/views/browser/index.vue
  src/views/configs/index.vue
  src/views/editor/index.vue
  src/views/executor/index.vue
  src/views/explorer/index.vue
  src/views/identity/index.vue
  src/views/inspector/index.vue
  vue.config.js
  yarn.lock
Labels: playground, production, review
