Repository aeternity/aepp-playground, pull requests merged in 2019-04, with the labels that each got.

#88 Hotfix/collapse improvment
  src/components/aepp-collapse.vue
  src/sections/aepp-nav.vue
  src/views/editor/index.vue
Labels: enhancement, review

#91 Feature/scrollbar
  package-lock.json
  package.json
  src/assets/styles/libraries/vuebar.css
  src/assets/styles/local/rules.css
  src/assets/styles/tailwind.css
  src/components/aepp-collapse.vue
  src/components/aepp-scrollbar.vue
  src/main.js
  src/views/editor/index.vue
Labels: review

#94 Package Upgrades and hotfixes
  .env
  .env.production
  package-lock.json
  package.json
  src/components/aepp-input.vue
  src/main.js
  src/store/getters/index.js
  src/store/state/index.js
  src/views/editor/index.vue
Labels: review

#95 hiding icons
  src/components/aepp-iframe.vue
Labels: review

#96 remove redundant files and folders from the project
  docker-compose.yml
  docker/accounts_test.json
  docker/aeternity_node1_mean15.yaml
  docker/aeternity_node2_mean15.yaml
  docker/aeternity_node3_mean15.yaml
  docker/entrypoint.sh
  docker/healthcheck.sh
  docker/keys/beneficiary/key
  docker/keys/beneficiary/key.pub
  docker/keys/node1/peer_key
  docker/keys/node1/peer_key.pub
  docker/keys/node2/peer_key
  docker/keys/node2/peer_key.pub
  docker/keys/node3/peer_key
  docker/keys/node3/peer_key.pub
  docker/nginx-cors.conf
  docker/nginx-default.conf
  docker/nginx-ws.conf
  examples/.gitignore
  examples/README.md
  examples/babel.config.js
  examples/package-lock.json
  examples/package.json
  examples/public/favicon.ico
  examples/public/index.html
  examples/src/App.vue
  examples/src/assets/logo.png
  examples/src/components/example.vue
  examples/src/main.js
  faucet.json
  faucet/index.js
  faucet/utils.js
  package.json
Labels: review

#98 Merge develop branch into master for new release
  .env
  .env.production
  docker-compose.yml
  docker/accounts_test.json
  docker/aeternity_node1_mean15.yaml
  docker/aeternity_node2_mean15.yaml
  docker/aeternity_node3_mean15.yaml
  docker/entrypoint.sh
  docker/healthcheck.sh
  docker/keys/beneficiary/key
  docker/keys/beneficiary/key.pub
  docker/keys/node1/peer_key
  docker/keys/node1/peer_key.pub
  docker/keys/node2/peer_key
  docker/keys/node2/peer_key.pub
  docker/keys/node3/peer_key
  docker/keys/node3/peer_key.pub
  docker/nginx-cors.conf
  docker/nginx-default.conf
  docker/nginx-ws.conf
  examples/.gitignore
  examples/README.md
  examples/babel.config.js
  examples/package-lock.json
  examples/package.json
  examples/public/favicon.ico
  examples/public/index.html
  examples/src/App.vue
  examples/src/assets/logo.png
  examples/src/components/example.vue
  examples/src/main.js
  faucet.json
  faucet/index.js
  faucet/utils.js
  package-lock.json
  package.json
  src/aepp.vue
  src/assets/styles/libraries/vuebar.css
  src/assets/styles/local/rules.css
  src/assets/styles/tailwind.css
  src/components/aepp-accordion.vue
  src/components/aepp-button-link.vue
  src/components/aepp-collapse.vue
  src/components/aepp-iframe.vue
  src/components/aepp-input.vue
  src/components/aepp-scrollbar.vue
  src/main.js
  src/sections/aepp-nav.vue
  src/store/getters/index.js
  src/store/state/index.js
  src/views/editor/index.vue
  tailwind.js
Labels: review

#100 Fix init constructor arugments when deployed
  src/views/editor/index.vue
Labels: review

#104 Add default wallet for testnet in the configuration
  .env
  .env.production
  src/store/state/index.js
Labels: review

#107 Hotfix/cleanup
  .env
  .env.production
  package.json
  src/components/aepp-editor.vue
  src/main.js
  src/plugins/wallet.js
  src/store/actions/index.js
  src/store/modules/contracts/actions.js
  src/store/modules/contracts/getters.js
  src/store/modules/contracts/index.js
  src/store/modules/contracts/mutations.js
  src/store/modules/contracts/state.js
  src/store/modules/index.js
  src/store/mutations/index.js
  src/store/state/index.js
Labels: playground, review

#111 Updates on the code
  src/aepp.vue
Labels: review

#106 upgrading packages
  package-lock.json
  package.json
Labels: playground, review

#105 small mvp terminal
  package-lock.json
  package.json
  src/sections/aepp-terminal.vue
  src/store/modules/index.js
  src/store/modules/terminal/actions.js
  src/store/modules/terminal/getters.js
  src/store/modules/terminal/index.js
  src/store/modules/terminal/mutations.js
  src/store/modules/terminal/state.js
  src/store/mutations/index.js
  src/views/editor/index.vue
  src/views/routes.js
Labels: playground, review
